#!/usr/bin/env python3
"""Collect every flagged record in the delivered dataset into one CSV.

Every anomaly turned up while building and reviewing this corpus, in one
sheet, one row per flagged pair, so the decision about what to do with each
class can be made by reading rather than by trusting a summary.

Rows are keyed by `row_index`, the 0-based line number in
output/dataset/qa_pairs.jsonl, so anything decided here maps back to the
deliverable exactly -- `sed -n "$((row_index+1))p" qa_pairs.jsonl`.

Flags (a row can carry several; `flags` joins them with ";"):

  latin_in_answer       the answer contains Latin letters. The prompt
                        forbids Latin script outright, so this is an
                        objective violation -- though a Latin proper noun
                        or citation is a legitimate reason for it to fire.
  sorani_context        context_mode is with_context AND the context text
                        reads as Sorani. This is the one that actually
                        leaks: the Q/A is Bahdini, but the Sorani context
                        goes into the training prompt.
  sorani_answer         the generated answer itself reads as Sorani.
  offlist_question_type question_type is not one of the five agreed types.
  offpipeline_model     the chunk was generated by the one-off
                        gemini-3.1-pro-self-antigravity experiment, not by
                        generate_qa_openrouter.py.
  missing_context       chunk_id no longer exists in chunks.jsonl, orphaned
                        by the post-corruption-fix corpus rebuild.
  long_prompt           system+question+context exceeds the 1300-token flag
                        threshold (a 30% allowance over the ~1,000 mean).
  duplicate_question    an identical question string appeared earlier;
                        `duplicate_of_row` points at the first occurrence.

The Sorani flags use the marker-frequency heuristic described in the README
and are **the weakest signal here** -- no validated threshold, and several
markers occur in both dialects. They are included because they point at a
real problem, not because the count is trustworthy. Treat them as a queue
to read, not a verdict; `sorani_score`/`bahdini_score` are exposed so the
cutoff can be re-judged in the spreadsheet.

Run inside the conda "ai" env, from the repo root:
    python3 qa_generation/export_outliers.py
    python3 qa_generation/export_outliers.py --context-chars 0   # full context
"""

import argparse
import csv
import glob
import hashlib
import json
import re
import sys
import time
from collections import Counter

import gemma_tokenizer as gtok
import qa_config as cfg

PROMPT_TOKEN_FLAG_THRESHOLD = 1300

# Only tokenize records long enough to plausibly exceed the threshold.
# Chunks are capped at MAX_CHUNK_TOKENS (1050) and this corpus measures
# 1.9-2.2 chars/token, with the document gate rejecting anything under 1.5;
# at the 1.5 floor, 1300 tokens is ~1950 characters. Below that a record
# cannot reach the threshold, so tokenizing it is wasted work.
TOKENIZE_MIN_CHARS = 1900

LATIN_RE = re.compile(r"[A-Za-z]")
LATIN_RUN_RE = re.compile(r"[A-Za-z][A-Za-z\s.'-]{2,}")

SORANI_MARKERS = [r"ەکان", r"ەکەی", r"\bلە\b", r"\bدە[کچب]", r"\bلەگەڵ\b",
                  r"\bئەم\b", r"\bکردووە\b", r"\bدەکات\b", r"\bبۆ\b"]
BAHDINI_MARKERS = [r"\bژ\b", r"\bدگەل\b", r"\bدڤێت\b", r"\bئەڤ\b", r"\bهەروەسا\b",
                   r"\bخۆ\b", r"\bیێن\b", r"\bب ", r"\bکرن\b"]
SORANI_RE = re.compile("|".join(SORANI_MARKERS))
BAHDINI_RE = re.compile("|".join(BAHDINI_MARKERS))
SORANI_RATIO = 1.5          # how far Sorani must lead before the flag fires

COLUMNS = [
    "row_index", "flags",
    "flag_latin_in_answer", "flag_sorani_context", "flag_sorani_answer",
    "flag_offlist_question_type", "flag_offpipeline_model",
    "flag_missing_context", "flag_long_prompt", "flag_duplicate_question",
    "source", "origin", "question_type", "context_mode",
    "document_id", "chunk_id",
    "question", "answer", "reasoning",
    "latin_chars_in_answer", "latin_sample",
    "sorani_score", "bahdini_score",
    "prompt_tokens", "duplicate_of_row",
    "context",
]


def leans_sorani(text: str):
    """(sorani_hits, bahdini_hits, is_sorani)."""
    s = len(SORANI_RE.findall(text))
    b = len(BAHDINI_RE.findall(text))
    return s, b, s > b * SORANI_RATIO and s > 0


def offpipeline_chunk_ids() -> set:
    """chunk_ids generated by anything other than this pipeline's script."""
    out = set()
    for path in glob.glob(str(cfg.GENERATIONS_DIR / "*" / "*.jsonl")):
        for line in open(path, encoding="utf-8"):
            if "antigravity" not in line:
                continue        # cheap prefilter; the vast majority skip here
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue
            if record.get("model") not in cfg.OPENROUTER_PRICING:
                out.add(record["chunk_id"])
    return out


def chunk_offsets() -> dict:
    index = {}
    with cfg.CHUNKS_PATH.open(encoding="utf-8") as handle:
        offset = handle.tell()
        line = handle.readline()
        while line:
            nxt = handle.tell()
            try:
                key_end = line.index('"chunk_id"') + 10
                vs = line.index('"', key_end) + 1
                index[line[vs:line.index('"', vs)]] = offset
            except ValueError:
                index[json.loads(line)["chunk_id"]] = offset
            offset = nxt
            line = handle.readline()
    return index


def split_user(user: str):
    """(context_or_None, question) from the delivered user message."""
    if user.startswith("Context: "):
        # rpartition: the question is last, and a context could in principle
        # contain the separator itself.
        context, sep, question = user.rpartition("\n\nQuestion: ")
        if sep:
            return context[len("Context: "):], question
        return user[len("Context: "):], ""
    if user.startswith("Question: "):
        return None, user[len("Question: "):]
    return None, user


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--context-chars", type=int, default=1200,
                        help="truncate the context column (default: 1200, enough to "
                             "judge dialect; 0 keeps the full chunk)")
    parser.add_argument("--max-tokenize", type=int, default=80_000,
                        help="cap on how many long records get tokenized for the "
                             "long_prompt flag (default: 80000)")
    args = parser.parse_args()

    src = cfg.DATASET_DIR / "qa_pairs.jsonl"
    if not src.is_file():
        sys.exit(f"{src} does not exist; run compile_qa_dataset.py first.")

    print("Finding off-pipeline chunk_ids ...")
    offpipeline = offpipeline_chunk_ids()
    print(f"  {len(offpipeline):,} chunks from the one-off experiment")

    print("Indexing chunks.jsonl ...")
    offsets = chunk_offsets()
    print(f"  {len(offsets):,} chunks indexed")

    out_path = cfg.DATASET_DIR / "qa_outliers.csv"
    counts = Counter()
    seen_questions = {}
    tokenized = 0
    tokenize_capped = False
    total = flagged = 0
    started = time.time()

    with src.open(encoding="utf-8") as fh, \
            cfg.CHUNKS_PATH.open(encoding="utf-8") as chunks_fh, \
            out_path.open("w", encoding="utf-8-sig", newline="") as out_fh:
        writer = csv.DictWriter(out_fh, fieldnames=COLUMNS, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()

        for row_index, line in enumerate(fh):
            line = line.strip()
            if not line:
                continue
            record = json.loads(line)
            total += 1
            messages = {m["role"]: m for m in record["messages"]}
            meta = record["metadata"]
            user = messages["user"]["content"]
            answer = messages["assistant"]["content"]
            reasoning = messages["assistant"].get("reasoning") or ""
            context, question = split_user(user)

            flags = []

            latin = LATIN_RE.findall(answer)
            latin_sample = ""
            if latin:
                flags.append("latin_in_answer")
                runs = LATIN_RUN_RE.findall(answer)
                latin_sample = " | ".join(r.strip() for r in runs[:3])[:160] \
                    or "".join(latin[:40])

            # For no_context records the context is not in the message, but
            # it is still what the pair was grounded in, so fetch it.
            missing = False
            if context is None:
                offset = offsets.get(meta["chunk_id"])
                if offset is None:
                    missing = True
                    context = ""
                else:
                    chunks_fh.seek(offset)
                    context = json.loads(chunks_fh.readline())["text"]
            elif meta["chunk_id"] not in offsets:
                missing = True
            if missing:
                flags.append("missing_context")

            s_ctx, b_ctx, ctx_sorani = leans_sorani(context)
            if ctx_sorani and meta["context_mode"] == "with_context":
                flags.append("sorani_context")
            _, _, ans_sorani = leans_sorani(answer)
            if ans_sorani:
                flags.append("sorani_answer")

            if meta["question_type"] not in cfg.QUESTION_TYPES:
                flags.append("offlist_question_type")
            if meta["chunk_id"] in offpipeline:
                flags.append("offpipeline_model")

            prompt_tokens = ""
            if len(user) >= TOKENIZE_MIN_CHARS:
                if tokenized < args.max_tokenize:
                    n = gtok.count_prompt_tokens(
                        [messages["system"], messages["user"]])
                    tokenized += 1
                    prompt_tokens = n
                    if n > PROMPT_TOKEN_FLAG_THRESHOLD:
                        flags.append("long_prompt")
                else:
                    tokenize_capped = True

            digest = hashlib.blake2b(question.encode("utf-8"), digest_size=8).digest()
            duplicate_of = ""
            if digest in seen_questions:
                flags.append("duplicate_question")
                duplicate_of = seen_questions[digest]
            else:
                seen_questions[digest] = row_index

            if not flags:
                continue

            flagged += 1
            for flag in flags:
                counts[flag] += 1

            writer.writerow({
                "row_index": row_index,
                "flags": ";".join(flags),
                "flag_latin_in_answer": int("latin_in_answer" in flags),
                "flag_sorani_context": int("sorani_context" in flags),
                "flag_sorani_answer": int("sorani_answer" in flags),
                "flag_offlist_question_type": int("offlist_question_type" in flags),
                "flag_offpipeline_model": int("offpipeline_model" in flags),
                "flag_missing_context": int("missing_context" in flags),
                "flag_long_prompt": int("long_prompt" in flags),
                "flag_duplicate_question": int("duplicate_question" in flags),
                "source": meta["source"],
                "origin": meta["chunk_id"].split("-", 1)[0],
                "question_type": meta["question_type"],
                "context_mode": meta["context_mode"],
                "document_id": meta["document_id"],
                "chunk_id": meta["chunk_id"],
                "question": question,
                "answer": answer,
                "reasoning": reasoning,
                "latin_chars_in_answer": len(latin),
                "latin_sample": latin_sample,
                "sorani_score": s_ctx,
                "bahdini_score": b_ctx,
                "prompt_tokens": prompt_tokens,
                "duplicate_of_row": duplicate_of,
                "context": context if args.context_chars <= 0
                           else context[:args.context_chars],
            })

            if flagged % 100_000 == 0:
                print(f"  {flagged:,} flagged of {total:,} scanned "
                      f"({time.time() - started:.0f}s)")

    print(f"\nScanned {total:,} records in {time.time() - started:.0f}s")
    print(f"Flagged {flagged:,} ({flagged / total * 100:.2f}%) -> {out_path} "
          f"({out_path.stat().st_size / 1e6:.1f} MB)")
    print(f"Tokenized {tokenized:,} long records for the long_prompt check"
          + (" (CAP HIT -- raise --max-tokenize for full coverage)"
             if tokenize_capped else ""))
    print("\nby flag (a row can carry several):")
    for flag, n in counts.most_common():
        print(f"  {flag:<24} {n:>9,}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
